# Generated by Django 5.0.3 on 2024-04-27 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=12)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realstate.role')),
            ],
        ),
    ]
