# Generated by Django 5.0.3 on 2024-04-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0004_employee_info_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='Employee_Tree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='Set_Manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='Set_Team_Head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='Team_Head_Detail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='Team_Manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='department',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='employee_Information',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='employee_Report',
            field=models.BooleanField(default=False),
        ),
    ]
