# Generated by Django 5.0.3 on 2024-04-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0005_role_employee_tree_role_set_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_and_menu',
            field=models.BooleanField(default=False),
        ),
    ]
