# Generated by Django 5.0.3 on 2024-05-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0007_rename_borker_role_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='customerwise_stagewise_due',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='plan_stage_wise_due',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='stage_wise_due',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='tower_wise_due',
            field=models.BooleanField(default=False),
        ),
    ]
