# Generated by Django 5.0.3 on 2024-05-07 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0008_role_customerwise_stagewise_due_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='proect_configuration_details',
            new_name='project_configuration_details',
        ),
    ]
