# Generated by Django 5.0.3 on 2024-05-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0009_rename_proect_configuration_details_role_project_configuration_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='intrest_calculator',
            field=models.BooleanField(default=False),
        ),
    ]
