# Generated by Django 5.0.3 on 2024-05-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0010_role_intrest_calculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='email_setup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='reports',
            field=models.BooleanField(default=False),
        ),
    ]
