# Generated by Django 5.0.1 on 2024-02-06 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("supermarkets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment",
        ),
    ]
