# Generated by Django 4.2.6 on 2023-11-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('on the way', 'on the way'), ('cancel', 'cancel'), ('deliverd', 'deliverd')], default='pending', max_length=50),
        ),
    ]
