# Generated by Django 5.0.3 on 2024-03-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0002_home_spldeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amountpaid',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='othercharges',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out For Delivery', 'Out For Delivery'), ('Cancel', 'Cancel'), ('Deliverd', 'Deliverd'), ('Return', 'Return'), ('Packing', 'Packing')], default='pending', max_length=50),
        ),
    ]
