# Generated by Django 5.0.1 on 2024-01-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supermarkets", "0002_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ManyToManyField(to="supermarkets.customer"),
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ManyToManyField(to="supermarkets.product"),
        ),
    ]
