# Generated by Django 5.0.1 on 2024-01-27 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("supermarkets", "0003_remove_order_customer_remove_order_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="prodapp",
        ),
    ]
