# Generated by Django 5.0.3 on 2024-03-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0003_alter_mobile_ad_image_1_alter_mobile_ad_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
