# Generated by Django 5.0.1 on 2024-02-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supermarkets", "0003_alter_customer_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="locality",
            field=models.TextField(),
        ),
    ]
