# Generated by Django 5.0.3 on 2024-03-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0003_order_amountpaid_order_othercharges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amountpaid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='othercharges',
            field=models.IntegerField(blank=True),
        ),
    ]
