# Generated by Django 5.0.1 on 2024-01-27 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("supermarkets", "0004_remove_product_prodapp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="discounted_price",
            new_name="discount",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="selling_price",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="title",
            new_name="productname",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="composition",
            new_name="specifications",
        ),
    ]
