# Generated by Django 5.0.2 on 2024-02-27 10:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0005_mobile_ads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mobile_ads',
            new_name='mobile_ad',
        ),
    ]
