# Generated by Django 5.0.1 on 2024-01-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supermarkets", "0005_rename_discounted_price_product_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.TextField(max_length=20),
        ),
    ]
