# Generated by Django 5.0.3 on 2024-03-25 09:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0006_poppularproducts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='poppularproducts',
            new_name='poppularproduct',
        ),
    ]
