# Generated by Django 5.0.1 on 2024-01-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supermarkets", "0006_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(upload_to="product/"),
        ),
    ]
