# Generated by Django 5.0.2 on 2024-02-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0006_rename_mobile_ads_mobile_ad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mobile_ad',
        ),
    ]
