# Generated by Django 5.0.2 on 2024-02-27 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0007_delete_mobile_ad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mobile_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(blank=True, upload_to='modiles/')),
                ('image_2', models.ImageField(blank=True, upload_to='modiles/')),
                ('image_3', models.ImageField(blank=True, upload_to='modiles/')),
                ('image_4', models.ImageField(blank=True, upload_to='modiles/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
