# Generated by Django 5.0.3 on 2024-03-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0007_rename_poppularproducts_poppularproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentsearch',
            old_name='product',
            new_name='recent',
        ),
    ]
