# Generated by Django 5.0.3 on 2024-03-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0014_rename_top_dealsproduct_top_deals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poppularproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='poppularproduct',
            name='user',
        ),
        migrations.RemoveField(
            model_name='suggestionproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='suggestionproduct',
            name='user',
        ),
        migrations.DeleteModel(
            name='NEW_LAUNCHINGproduct',
        ),
        migrations.DeleteModel(
            name='poppularproduct',
        ),
        migrations.DeleteModel(
            name='Suggestionproduct',
        ),
    ]
