# Generated by Django 5.0.3 on 2024-03-30 14:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0015_remove_poppularproduct_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Festivalproduct',
            new_name='Festival_offer',
        ),
    ]
