# Generated by Django 5.0.3 on 2024-04-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0018_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='quality',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
