# Generated by Django 5.0.3 on 2024-04-11 10:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0019_cart_items_quality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart_items',
            new_name='cart',
        ),
    ]
