# Generated by Django 5.0.3 on 2024-04-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0020_rename_cart_items_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart_item',
        ),
    ]
