# Generated by Django 5.0.3 on 2024-04-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0024_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
