# Generated by Django 5.0.3 on 2024-04-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0026_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.TextField(blank=True),
        ),
    ]
